### ISSUE TITLE
How to evaluate provided mesh result?

### ISSUE THREAD

**Issue by Pixie8888** [kyleleey/RICO#8]
Hi,

It seems that the [provided mesh](https://drive.google.com/drive/folders/1fq6k56q7CU21KrAAJ9SUIQyhM2FvqmpT) is not aligned with scannet GT mesh (scenexxxx_vh_clean_2.ply), ie they are in different coordinates and scales are different. When I naively borrowed the evaluation code from monosdf, the results are very bad. How to align your provided mesh with GT mesh so that I can evaluate it?

Another question, the visualization of my result has more messy background than your provided mesh. Do you use post processing? And will these post processing affect the quantitative evaluation result (since the mesh looks cleaner)?
My mesh:
<img width="627" alt="image" src="https://github.com/kyleleey/RICO/assets/72333326/fa470335-14e1-4b9f-8342-c4400141df1b">
your mesh:
<img width="565" alt="image" src="https://github.com/kyleleey/RICO/assets/72333326/719f90ee-ed4e-41d6-be72-011e4ac5a70a">

**Comment by Pixie8888** [comment]
oh sorry I realised how to evaluate your mesh. 
But, could you please explain the second question? Thank you very much!

**Comment by kyleleey** [comment]
Ithink the second mesh is extracted by using the formal post-processing used in MonoSDF / ManhattanSDF

**Comment by Pixie8888** [comment]
thanks!

**Comment by Pixie8888** [comment]
Hi, I have another question regarding validation process. I found it is very easy to encounter OOM issue when generating sdf and mesh. I am running on a RTX 3090 Ti. Do you know how to solve this problem? 
```
Traceback (most recent call last):
  File "training/exp_runner.py", line 107, in <module>
    trainrunner.run()
  File "/data/ytxu/nerf/RICO/code/../code/training/rico_train.py", line 224, in run
    plt.plot_rico(
  File "/data/ytxu/nerf/RICO/code/../code/utils/plots.py", line 81, in plot_rico
    _ = get_surface_sliding(
  File "/data/ytxu/anaconda3/envs/rico/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/data/ytxu/nerf/RICO/code/../code/utils/plots.py", line 173, in get_surface_sliding
    pts_sdf_eval = evaluate(pts_to_eval.contiguous())
  File "/data/ytxu/nerf/RICO/code/../code/utils/plots.py", line 147, in evaluate
    z.append(sdf(pnts))
  File "/data/ytxu/nerf/RICO/code/../code/utils/plots.py", line 84, in <lambda>
    sdf = lambda x: implicit_network(x)[:, indx],
  File "/data/ytxu/anaconda3/envs/rico/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/ytxu/nerf/RICO/code/../code/model/network_rico.py", line 187, in forward
    x = lin(x)
  File "/data/ytxu/anaconda3/envs/rico/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1148, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/data/ytxu/anaconda3/envs/rico/lib/python3.8/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: CUDA out of memory. Tried to allocate 108.00 MiB (GPU 0; 22.19 GiB total capacity; 20.31 GiB already allocated; 48.69 MiB free; 21.16 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
/data/ytxu/anaconda3/envs/rico/lib/python3.8/site-packages/torch/distributed/launch.py:178: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
```

**Comment by kyleleey** [comment]
It seems the OOM happens in Marching Cubes stage.

I used the GPU with 40G memory, I would also recommend you set a smaller MC resolution, like 256 or 128, it won't affect the results too much.

And also, if the mesh results are naturally very big (occupies too much space), it would also consume a lot of space in MC

**Comment by Pixie8888** [comment]
Thanks a lot!
